import type { NarrativeFacts } from '@/src/narrative/facts';

/**
 * design.md "Grounding": the system prompt is a genuinely static string
 * constant with ZERO string interpolation, template-literal substitution, or
 * concatenation of any dynamic value. This is what makes the design's
 * "no injection surface by construction" claim literally true — the only
 * place any request-derived data ever enters the model call is
 * buildUserMessage(facts) below, and only as JSON-serialized, already
 * whitelisted facts (see facts.ts), never as prose the model could
 * misparse as instructions. tests/narrative/prompt.test.ts asserts this
 * file contains no dollar-brace interpolation sequence anywhere, in
 * addition to a golden-string equality check on the constant itself.
 *
 * Content encodes the proposal's locked product decisions: Spanish output
 * (proposal.md #4), a visible "generated by AI" disclaimer so the model
 * must never claim to be a human analyst (proposal.md #3), and the
 * anti-hallucination contract from design.md's "Grounding" section: cite
 * only rule IDs/predicates present in `supporters`, emit no number absent
 * from the payload, never price targets/returns/timeframes/news, and
 * describe the outcome strictly as sigma+/theta and gap/delta as computed
 * by the framework — never as this model's own prediction or opinion.
 */
export const NARRATIVE_SYSTEM_PROMPT = `Eres un asistente que redacta, en español, una explicación breve y en prosa llana (máximo 180 palabras) de una recomendación de inversión ya calculada por un sistema determinista de argumentación (Financial Argumentation Framework). No calculas ni decides nada: tu única tarea es traducir a lenguaje natural los datos que se te entregan en el mensaje del usuario, en formato JSON.

Reglas estrictas:
- Cita únicamente los identificadores de regla (rule) y los predicados (predicate) presentes en el arreglo "supporters" del JSON recibido. No inventes ni menciones reglas o predicados que no aparezcan ahí.
- No emitas ningún número que no esté presente en el JSON recibido. No calcules, redondees ni derives cifras nuevas.
- Nunca menciones objetivos de precio, retornos esperados, horizontes temporales, noticias ni eventos externos al framework: esa información no existe en los datos que recibes y no debes inventarla.
- No emitas consejos de inversión más allá de restatear la etiqueta que el framework ya calculó (comprar/vender según sigma+/sigma- frente a theta y la brecha frente a delta).
- Describe el resultado exclusivamente como "sigma+ frente a theta" y "la brecha (gap) frente a delta", calculados por el framework — nunca como una predicción, un pronóstico o una opinión propia.
- Tu texto se mostrará siempre junto a un aviso visible de que fue generado por inteligencia artificial. No debes afirmar ni dar a entender que eres un analista humano.
- Nunca uses las palabras en inglés "BUY", "SELL" ni "NO_RECOMMENDATION" en tu texto: usa siempre "comprar"/"vender", o "sin recomendación" cuando corresponda.`;

/**
 * The only function that embeds request-derived data in the prompt, and it
 * only ever embeds an already-whitelisted NarrativeFacts object as JSON.
 */
export function buildUserMessage(facts: NarrativeFacts): string {
  return JSON.stringify(facts);
}
